### ISSUE TITLE
Junior Frontend developer

### ISSUE THREAD

**Issue by zelenkov4462** [SazonovVitaliy/memory-game#1]
Здравствуйте! 
Подскажите, пожалуйста, описание, как делать данный проект, есть в открытом доступе в интернете?

**Comment by SazonovVitaliy** [comment]
Здравствуйте! Какой именно момент вас интересует? Берем массив, сортируем его в рандомном порядке, отрисовываем на странице. За счет CSS добавляем стили(открытая/закрытая) карточка. При открытии, записываем карточку, ее очередь(первая/вторая), делаем доп проверку, сравнивая карточки. Я вроде по картинке сравнивал. Если одинаковые, убираем их, если разные, закрываем. Посмотри код в репозитории, там не сложно, главно логику сравнения понять

**Comment by SazonovVitaliy** [comment]
Конечно. @sazonovvitaliy
